import { CountryProfile } from "./types";

export const europeProfiles: CountryProfile[] = [
  {
    id: 29,
    code: "RUS",
    nameEn: "Russia",
    nameFa: "روسیه",
    gdp: 1700000000000,
    population: 144000000,
    traits: ["OIL_RICH", "MILITARISTIC"],
    flagCode: "RU",
    startingTreasury: 500000,
    startingInfantry: 800,
    startingAirForce: 150,
    startingDroneMissile: 60,
    startingTechLevel: 4,
    startingGovernment: "DICTATORSHIP",
  },
  {
    id: 32,
    code: "NOR",
    nameEn: "Norway",
    nameFa: "نروژ",
    gdp: 580000000000,
    population: 5500000,
    traits: ["OIL_RICH", "INDUSTRIAL_HUB"],
    flagCode: "NO",
    startingTreasury: 450000,
    startingInfantry: 70,
    startingAirForce: 40,
    startingDroneMissile: 10,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 54,
    code: "FRA",
    nameEn: "France",
    nameFa: "فرانسه",
    gdp: 2900000000000,
    population: 68000000,
    traits: ["INDUSTRIAL_HUB", "MILITARISTIC"],
    flagCode: "FR",
    startingTreasury: 620000,
    startingInfantry: 220,
    startingAirForce: 70,
    startingDroneMissile: 25,
    startingTechLevel: 5,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 121,
    code: "SWE",
    nameEn: "Sweden",
    nameFa: "سوئد",
    gdp: 600000000000,
    population: 10500000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "SE",
    startingTreasury: 350000,
    startingInfantry: 80,
    startingAirForce: 45,
    startingDroneMissile: 10,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 122,
    code: "BLR",
    nameEn: "Belarus",
    nameFa: "بلاروس",
    gdp: 70000000000,
    population: 9300000,
    traits: ["ISOLATED_SOCIETY"],
    flagCode: "BY",
    startingTreasury: 120000,
    startingInfantry: 80,
    startingAirForce: 20,
    startingDroneMissile: 5,
    startingTechLevel: 2,
    startingGovernment: "DICTATORSHIP",
  },
  {
    id: 123,
    code: "UKR",
    nameEn: "Ukraine",
    nameFa: "اوکراین",
    gdp: 160000000000,
    population: 38000000,
    traits: ["MILITARISTIC", "FRAGILE_ECONOMY"],
    flagCode: "UA",
    startingTreasury: 180000,
    startingInfantry: 550,
    startingAirForce: 50,
    startingDroneMissile: 40,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 124,
    code: "POL",
    nameEn: "Poland",
    nameFa: "لهستان",
    gdp: 700000000000,
    population: 38000000,
    traits: ["MILITARISTIC", "INDUSTRIAL_HUB"],
    flagCode: "PL",
    startingTreasury: 380000,
    startingInfantry: 220,
    startingAirForce: 50,
    startingDroneMissile: 20,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 125,
    code: "AUT",
    nameEn: "Austria",
    nameFa: "اتریش",
    gdp: 480000000000,
    population: 9000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "AT",
    startingTreasury: 310000,
    startingInfantry: 50,
    startingAirForce: 20,
    startingDroneMissile: 2,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 126,
    code: "HUN",
    nameEn: "Hungary",
    nameFa: "مجارستان",
    gdp: 180000000000,
    population: 9700000,
    traits: ["ISOLATED_SOCIETY"],
    flagCode: "HU",
    startingTreasury: 170000,
    startingInfantry: 60,
    startingAirForce: 20,
    startingDroneMissile: 5,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 128,
    code: "ROU",
    nameEn: "Romania",
    nameFa: "رومانی",
    gdp: 300000000000,
    population: 19000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "RO",
    startingTreasury: 220000,
    startingInfantry: 110,
    startingAirForce: 30,
    startingDroneMissile: 5,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 132,
    code: "DEU",
    nameEn: "Germany",
    nameFa: "آلمان",
    gdp: 4300000000000,
    population: 84000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "DE",
    startingTreasury: 750000,
    startingInfantry: 150,
    startingAirForce: 55,
    startingDroneMissile: 15,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 133,
    code: "BGR",
    nameEn: "Bulgaria",
    nameFa: "بلغارستان",
    gdp: 90000000000,
    population: 6800000,
    traits: ["FRAGILE_ECONOMY"],
    flagCode: "BG",
    startingTreasury: 100000,
    startingInfantry: 45,
    startingAirForce: 15,
    startingDroneMissile: 2,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 134,
    code: "GRC",
    nameEn: "Greece",
    nameFa: "یونان",
    gdp: 220000000000,
    population: 10400000,
    traits: ["ISLAND_FORTRESS", "MILITARISTIC"],
    flagCode: "GR",
    startingTreasury: 150000,
    startingInfantry: 150,
    startingAirForce: 45,
    startingDroneMissile: 10,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 135,
    code: "TUR",
    nameEn: "Turkey",
    nameFa: "ترکیه",
    gdp: 900000000000,
    population: 85000000,
    traits: ["INDUSTRIAL_HUB", "MILITARISTIC"],
    flagCode: "TR",
    startingTreasury: 380000,
    startingInfantry: 400,
    startingAirForce: 60,
    startingDroneMissile: 45,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 137,
    code: "HRV",
    nameEn: "Croatia",
    nameFa: "کرواسی",
    gdp: 70000000000,
    population: 3800000,
    traits: ["ISLAND_FORTRESS"],
    flagCode: "HR",
    startingTreasury: 120000,
    startingInfantry: 40,
    startingAirForce: 15,
    startingDroneMissile: 2,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 138,
    code: "CHE",
    nameEn: "Switzerland",
    nameFa: "سوئیس",
    gdp: 800000000000,
    population: 8800000,
    traits: ["SOVEREIGN_FORTRESS", "INDUSTRIAL_HUB"],
    flagCode: "CH",
    startingTreasury: 480000,
    startingInfantry: 60,
    startingAirForce: 35,
    startingDroneMissile: 5,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 140,
    code: "BEL",
    nameEn: "Belgium",
    nameFa: "بلژیک",
    gdp: 580000000000,
    population: 11700000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "BE",
    startingTreasury: 350000,
    startingInfantry: 50,
    startingAirForce: 30,
    startingDroneMissile: 5,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 141,
    code: "NLD",
    nameEn: "Netherlands",
    nameFa: "هلند",
    gdp: 1000000000000,
    population: 17800000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "NL",
    startingTreasury: 420000,
    startingInfantry: 80,
    startingAirForce: 40,
    startingDroneMissile: 10,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 142,
    code: "PRT",
    nameEn: "Portugal",
    nameFa: "پرتغال",
    gdp: 250000000000,
    population: 10300000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "PT",
    startingTreasury: 220000,
    startingInfantry: 50,
    startingAirForce: 20,
    startingDroneMissile: 2,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 143,
    code: "ESP",
    nameEn: "Spain",
    nameFa: "اسپانیا",
    gdp: 1400000000000,
    population: 47000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "ES",
    startingTreasury: 390000,
    startingInfantry: 140,
    startingAirForce: 45,
    startingDroneMissile: 10,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 144,
    code: "IRL",
    nameEn: "Ireland",
    nameFa: "ایرلند",
    gdp: 500000000000,
    population: 5100000,
    traits: ["ISLAND_FORTRESS"],
    flagCode: "IE",
    startingTreasury: 250000,
    startingInfantry: 40,
    startingAirForce: 15,
    startingDroneMissile: 0,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 152,
    code: "ITA",
    nameEn: "Italy",
    nameFa: "ایتالیا",
    gdp: 2000000000000,
    population: 59000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "IT",
    startingTreasury: 480000,
    startingInfantry: 160,
    startingAirForce: 55,
    startingDroneMissile: 15,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 153,
    code: "DNK",
    nameEn: "Denmark",
    nameFa: "دانمارک",
    gdp: 400000000000,
    population: 5900000,
    traits: ["ISLAND_FORTRESS"],
    flagCode: "DK",
    startingTreasury: 310000,
    startingInfantry: 45,
    startingAirForce: 25,
    startingDroneMissile: 2,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 154,
    code: "GBR",
    nameEn: "United Kingdom",
    nameFa: "بریتانیا",
    gdp: 3100000000000,
    population: 67000000,
    traits: ["ISLAND_FORTRESS", "MILITARISTIC"],
    flagCode: "GB",
    startingTreasury: 650000,
    startingInfantry: 180,
    startingAirForce: 65,
    startingDroneMissile: 20,
    startingTechLevel: 5,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 155,
    code: "ISL",
    nameEn: "Iceland",
    nameFa: "ایسلند",
    gdp: 28000000000,
    population: 380000,
    traits: ["ISLAND_FORTRESS", "ISOLATED_SOCIETY"],
    flagCode: "IS",
    startingTreasury: 150000,
    startingInfantry: 10,
    startingAirForce: 0,
    startingDroneMissile: 0,
    startingTechLevel: 1,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 162,
    code: "FIN",
    nameEn: "Finland",
    nameFa: "فنلاند",
    gdp: 300000000000,
    population: 5600000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "FI",
    startingTreasury: 250000,
    startingInfantry: 90,
    startingAirForce: 35,
    startingDroneMissile: 10,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 163,
    code: "SVK",
    nameEn: "Slovakia",
    nameFa: "اسلواکی",
    gdp: 115000000000,
    population: 5400000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "SK",
    startingTreasury: 140000,
    startingInfantry: 45,
    startingAirForce: 15,
    startingDroneMissile: 2,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 164,
    code: "CZE",
    nameEn: "Czechia",
    nameFa: "جمهوری چک",
    gdp: 29000000000,
    population: 10500000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "CZ",
    startingTreasury: 210000,
    startingInfantry: 65,
    startingAirForce: 25,
    startingDroneMissile: 5,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 182,
    code: "SRB",
    nameEn: "Serbia",
    nameFa: "صربستان",
    gdp: 65000000000,
    population: 6800000,
    traits: ["MILITARISTIC"],
    flagCode: "RS",
    startingTreasury: 110000,
    startingInfantry: 65,
    startingAirForce: 20,
    startingDroneMissile: 5,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 184,
    code: "KOS",
    nameEn: "Kosovo",
    nameFa: "کوزوو",
    gdp: 9000000000,
    population: 1800000,
    traits: ["SOVEREIGN_FORTRESS", "FRAGILE_ECONOMY"],
    flagCode: "XK",
    startingTreasury: 60000,
    startingInfantry: 20,
    startingAirForce: 0,
    startingDroneMissile: 0,
    startingTechLevel: 1,
    startingGovernment: "DEMOCRACY",
  },
];
