export interface ResearchNode {
  id: string;
  nameFa: string;
  desc: string;
  branch: "INDUSTRIAL_TECH" | "ASYMMETRIC_MILITARY" | "DIPLOMATIC_HEGEMONY";
  tier: 1 | 2 | 3;
  moneyCost: number;
  prerequisites: string[];
}

export const COMPREHENSIVE_RESEARCH_TREE: ResearchNode[] = [
  {
    id: "gdp-booster",
    nameFa: "اتوماسیون خطوط تولید",
    desc: "مکانیزه‌سازی صنایع کشوری که ۵٪ افزایش دائمی در درآمد مالیات صنعتی ایجاد می‌کند.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    moneyCost: 15000000000,
    prerequisites: [],
  },
  {
    id: "urban-expansion",
    nameFa: "توسعه زیست‌شهری و مسکن",
    desc: "بهینه‌سازی شهرسازی که ظرفیت زیستی و مسکن کشور را ۱۵٪ افزایش می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    moneyCost: 20000000000,
    prerequisites: [],
  },
  {
    id: "advanced-education",
    nameFa: "تکنولوژی آموزش تخصصی",
    desc: "ارتقای سطح دانش نیروی کار که رشد بهره‌وری سرانه را در هر نوبت شتاب می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 2,
    moneyCost: 45000000000,
    prerequisites: ["urban-expansion"],
  },
  {
    id: "cybernetic-automation",
    nameFa: "هوش مصنوعی و سایبرنتیک صنعتی",
    desc: "حداکثرسازی بازدهی صنایع که ۱۵٪ به درآمد مالیات افزوده و ۲۰٪ هزینه ساخت یگان‌ها را کم می‌کند.",
    branch: "INDUSTRIAL_TECH",
    tier: 3,
    moneyCost: 120000000000,
    prerequisites: ["gdp-booster", "advanced-education"],
  },
  {
    id: "border-fortification",
    nameFa: "دکترین استحکامات مرزی",
    desc: "ارتقای مواضع و پادگان‌های مرزی که پایداری و قدرت دفاعی کشور را افزایش می‌دهد.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    moneyCost: 18000000000,
    prerequisites: [],
  },
  {
    id: "tactical-drones",
    nameFa: "پهپادهای پایش تاکتیکی",
    desc: "شناسایی هوشمند میدان نبرد که کارایی و قدرت تخریب پهپادها و موشک‌ها را ۲۰٪ زیاد می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    moneyCost: 25000000000,
    prerequisites: [],
  },
  {
    id: "integrated-air-defense",
    nameFa: "سپر پدافند هوایی یکپارچه",
    desc: "پدافند موشکی پیشرفته که ۳۰٪ از پهپادها و موشک‌های شلیک‌شده دشمن را قبل از برخورد منهدم می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    moneyCost: 50000000000,
    prerequisites: ["border-fortification"],
  },
  {
    id: "precision-missiles",
    nameFa: "سامانه‌های بالستیک نقطه‌زن",
    desc: "افزایش ۲۵٪ قدرت تهاجمی موشک‌ها در حملات پیش‌دستانه به یگان‌های دشمن.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    moneyCost: 55000000000,
    prerequisites: ["tactical-drones"],
  },
  {
    id: "electronic-warfare",
    nameFa: "جنگ الکترونیک و دفاع سایبری",
    desc: "بی‌اثر کردن ۵۰٪ از برتری هوایی دشمن در نبردها و افزایش ۲۰٪ شانس فرار یگان‌های خودی.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 3,
    moneyCost: 130000000000,
    prerequisites: ["integrated-air-defense", "precision-missiles"],
  },
  {
    id: "global-influence",
    nameFa: "دیپلماسی تجاری کلان",
    desc: "انعقاد موافقت‌نامه‌های گمرکی که درآمد حاصل از تعرفه‌های تجاری را ۱۵٪ افزایش می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    moneyCost: 12000000000,
    prerequisites: [],
  },
  {
    id: "trade-diplomacy",
    nameFa: "تابش رسانه‌ای و دیپلماتیک",
    desc: "ارتقای تصویر بین‌المللی که ۱۰ واحد افزایش فوری و دائمی در اعتبار جهانی ایجاد می‌کند.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    moneyCost: 22000000000,
    prerequisites: [],
  },
  {
    id: "reputation-recovery",
    nameFa: "هژمونی رسانه‌های بین‌المللی",
    desc: "کنترل افکار عمومی که ۵۰٪ از افت ثبات ناشی از مالیات‌های سنگین را خنثی می‌کند.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    moneyCost: 40000000000,
    prerequisites: ["global-influence"],
  },
  {
    id: "proxy-network",
    nameFa: "شبکه جاسوسی و عملیات سایبری",
    desc: "کاهش ۲۵٪ هزینه اجرای تمام سطوح عملیات‌های ویژه و خرابکاری اطلاعاتی.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    moneyCost: 45000000000,
    prerequisites: ["trade-diplomacy"],
  },
  {
    id: "security-alliance",
    nameFa: "پیمان امنیت فراملی و هژمونی",
    desc: "تسهیل شگفت‌انگیز عقد ائتلاف‌های دفاعی با کاهش ۳۰ واحدی آستانه پذیرش نظر کشورهای خارجی.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 3,
    moneyCost: 110000000000,
    prerequisites: ["reputation-recovery", "proxy-network"],
  },
];
