export interface ResearchNode {
  id: string;
  nameFa: string;
  nameEn: string;
  desc: string;
  branch: "INDUSTRIAL_TECH" | "ASYMMETRIC_MILITARY" | "DIPLOMATIC_HEGEMONY";
  tier: 1 | 2 | 3;
  cost: number;
  prerequisites: string[];
  effectType: string;
  magnitude: number;
}

export const COMPREHENSIVE_RESEARCH_TREE: ResearchNode[] = [
  {
    id: "gdp-booster",
    nameFa: "اتوماسیون خطوط تولید",
    nameEn: "Automation Pipelines",
    desc: "مکانیزه‌سازی صنایع سنگین و خطوط تولید کشوری که باعث افزایش ۵٪ در رشد سالانه GDP می‌شود.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    cost: 3,
    prerequisites: [],
    effectType: "GDP_GROWTH_MULT",
    magnitude: 0.05,
  },
  {
    id: "low-upkeep",
    nameFa: "لجستیک سبز و بهینه‌سازی",
    nameEn: "Green Logistics Grid",
    desc: "کاهش اتلاف انرژی و بهینه‌سازی ناوگان حمل‌ونقل که هزینه‌های نگهداری را ۱۰٪ کاهش می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    cost: 4,
    prerequisites: [],
    effectType: "UPKEEP_MULT",
    magnitude: -0.1,
  },
  {
    id: "heavy-metallurgy",
    nameFa: "متالورژی صنعتی سنگین",
    nameEn: "Heavy Metallurgy",
    desc: "ارتقای کوره‌های ذوب و استخراج فولاد که نرخ تولید نوبتی فولاد را ۱۵٪ افزایش می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 2,
    cost: 6,
    prerequisites: ["gdp-booster"],
    effectType: "STEEL_PROD_MULT",
    magnitude: 0.15,
  },
  {
    id: "deep-refining",
    nameFa: "تکنولوژی پالایش عمیق",
    nameEn: "Deep Refining Tech",
    desc: "به‌کارگیری برج‌های تقطیر پیشرفته برای افزایش ۲۰٪ در بازدهی استخراج استراتژیک نفت.",
    branch: "INDUSTRIAL_TECH",
    tier: 2,
    cost: 6,
    prerequisites: ["low-upkeep"],
    effectType: "OIL_PROD_MULT",
    magnitude: 0.2,
  },
  {
    id: "cybernetic-automation",
    nameFa: "هوش مصنوعی و سایبرنتیک صنعتی",
    nameEn: "Cybernetic Industrial AI",
    desc: "حداکثرسازی بازدهی صنایع ملی با رباتیک شبکه که GDP را ۱۵٪ جهش می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 3,
    cost: 10,
    prerequisites: ["heavy-metallurgy", "deep-refining"],
    effectType: "GDP_GROWTH_MULT",
    magnitude: 0.15,
  },
  {
    id: "border-fortification",
    nameFa: "دکترین پادگان و استحکامات",
    nameEn: "Garrison Protocols",
    desc: "افزایش ۱۵٪ قدرت رزمی دفاعی پادگان‌ها و نیروهای انتظامی در برابر نفوذ.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    cost: 3,
    prerequisites: [],
    effectType: "MILITIA_POWER_MULT",
    magnitude: 0.15,
  },
  {
    id: "tactical-drones",
    nameFa: "پهپادهای پایش تاکتیکی",
    nameEn: "Tactical Recon Drones",
    desc: "شناسایی هوشمند میدان نبرد که کارایی یگان‌های موشکی و پهپادی را ۲۰٪ افزایش می‌دهد.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    cost: 4,
    prerequisites: [],
    effectType: "DRONE_POWER_MULT",
    magnitude: 0.2,
  },
  {
    id: "integrated-air-defense",
    nameFa: "پدافند هوایی یکپارچه",
    nameEn: "Integrated Air Defense",
    desc: "شبکه‌سازی رادارهای هشدار زودهنگام که تلفات نیروی هوایی در نبردها را ۲۰٪ کاهش می‌دهد.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    cost: 6,
    prerequisites: ["border-fortification"],
    effectType: "AIR_DEFENSE_BONUS",
    magnitude: 0.2,
  },
  {
    id: "precision-missiles",
    nameFa: "سامانه‌های بالستیک نقطه‌زن",
    nameEn: "Precision Ballistic Missiles",
    desc: "افزایش ۲۵٪ قدرت تخریب تهاجمی موشکی در حملات به اقالیم دشمن.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    cost: 7,
    prerequisites: ["tactical-drones"],
    effectType: "MISSILE_POWER_MULT",
    magnitude: 0.25,
  },
  {
    id: "electronic-warfare",
    nameFa: "جنگ الکترونیک و دفاع سایبری",
    nameEn: "Electronic Warfare Suite",
    desc: "کاهش ۳۰٪ تلفات کل یگان‌های نظامی از طریق کور کردن رادارهای پیشرفته دشمن.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 3,
    cost: 10,
    prerequisites: ["integrated-air-defense", "precision-missiles"],
    effectType: "MILITARY_CASUALTY_REDUCTION",
    magnitude: 0.3,
  },
  {
    id: "global-influence",
    nameFa: "تابش دیپلماتیک و رسانه‌ای",
    nameEn: "Cultural Radiance",
    desc: "ارتقای تصویر بین‌المللی کشور که اعتبار و پرستیژ جهانی را ۵ واحد بهبود می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    cost: 3,
    prerequisites: [],
    effectType: "REPUTATION_FLAT_BONUS",
    magnitude: 5,
  },
  {
    id: "trade-diplomacy",
    nameFa: "دیپلماسی تجاری کلان",
    nameEn: "Commercial Diplomacy",
    desc: "انعقاد موافقت‌نامه‌های گمرکی که درآمد حاصل از تعرفه‌های تجاری را ۱۰٪ افزایش می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    cost: 4,
    prerequisites: [],
    effectType: "TARIFF_REVENUE_MULT",
    magnitude: 0.1,
  },
  {
    id: "reputation-recovery",
    nameFa: "هژمونی رسانه‌ای بین‌المللی",
    nameEn: "Media Hegemony",
    desc: "افزایش ۵۰٪ سرعت بازیابی پرستیژ و اعتبار جهانی در پی بحران‌های سیاسی.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    cost: 6,
    prerequisites: ["global-influence"],
    effectType: "REPUTATION_RECOVERY_MULT",
    magnitude: 0.5,
  },
  {
    id: "proxy-network",
    nameFa: "شبکه نفوذ و عملیات نیابتی",
    nameEn: "Proxy Influence Network",
    desc: "کاهش ۲۰٪ هزینه اجرای عملیات‌های پنهان و نفوذ علیه ثبات سیاسی دشمنان.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    cost: 6,
    prerequisites: ["trade-diplomacy"],
    effectType: "PROXY_COST_DISCOUNT",
    magnitude: 0.2,
  },
  {
    id: "security-alliance",
    nameFa: "پیمان امنیت فراملی و هژمونی",
    nameEn: "Transnational Security Pact",
    desc: "تسهیل شگفت‌انگیز عقد ائتلاف‌های دفاعی مشترک و افزایش ثبات دیپلماتیک جهانی.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 3,
    cost: 10,
    prerequisites: ["reputation-recovery", "proxy-network"],
    effectType: "DIPLOMATIC_OPINION_MULT",
    magnitude: 0.3,
  },
];
