export interface ResearchNode {
  id: string;
  nameFa: string;
  nameEn: string;
  desc: string;
  branch: "INDUSTRIAL_TECH" | "ASYMMETRIC_MILITARY" | "DIPLOMATIC_HEGEMONY";
  tier: 1 | 2 | 3;
  moneyCost: number;
  prerequisites: string[];
  effectType: string;
  magnitude: number;
}

export const COMPREHENSIVE_RESEARCH_TREE: ResearchNode[] = [
  {
    id: "gdp-booster",
    nameFa: "اتوماسیون خطوط تولید",
    nameEn: "Automation Pipelines",
    desc: "مکانیزه‌سازی صنایع کشوری که ۵٪ افزایش دائمی در درآمد مالیات صنعتی ایجاد می‌کند.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    moneyCost: 15000000000,
    prerequisites: [],
    effectType: "TAX_YIELD_BOOST",
    magnitude: 0.05,
  },
  {
    id: "urban-expansion",
    nameFa: "توسعه زیست‌شهری و مسکن",
    nameEn: "Urban Expansion Grid",
    desc: "بهینه‌سازی شهرسازی که ظرفیت زیستی و مسکن کشور را ۱۵٪ افزایش می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    moneyCost: 20000000000,
    prerequisites: [],
    effectType: "HOUSING_CAPACITY_DISCOUNT",
    magnitude: 0.15,
  },
  {
    id: "advanced-education",
    nameFa: "تکنولوژی آموزش تخصصی",
    nameEn: "Advanced Technical Education",
    desc: "ارتقای سطح دانش نیروی کار که رشد بهره‌وری سرانه را در هر نوبت شتاب می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 2,
    moneyCost: 45000000000,
    prerequisites: ["urban-expansion"],
    effectType: "PRODUCTIVITY_BOOST",
    magnitude: 0.1,
  },
  {
    id: "cybernetic-automation",
    nameFa: "هوش مصنوعی و سایبرنتیک صنعتی",
    nameEn: "Cybernetic Industrial AI",
    desc: "حداکثرسازی بازدهی صنایع که ۱۵٪ به درآمد مالیات افزوده و ۲۰٪ هزینه ساخت یگان‌ها را کم می‌کند.",
    branch: "INDUSTRIAL_TECH",
    tier: 3,
    moneyCost: 120000000000,
    prerequisites: ["gdp-booster", "advanced-education"],
    effectType: "INDUSTRIAL_CYBERNETICS",
    magnitude: 0.15,
  },
  {
    id: "border-fortification",
    nameFa: "دکترین استحکامات مرزی",
    nameEn: "Garrison Protocols",
    desc: "ارتقای مواضع و پادگان‌های مرزی که پایداری و قدرت دفاعی کشور را افزایش می‌دهد.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    moneyCost: 18000000000,
    prerequisites: [],
    effectType: "BORDER_FORTIFICATION",
    magnitude: 0.25,
  },
  {
    id: "tactical-drones",
    nameFa: "پهپادهای پایش تاکتیکی",
    nameEn: "Tactical Recon Drones",
    desc: "شناسایی هوشمند میدان نبرد که کارایی و قدرت تخریب پهپادها و موشک‌ها را ۲۰٪ زیاد می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    moneyCost: 25000000000,
    prerequisites: [],
    effectType: "DRONE_POWER_BOOST",
    magnitude: 0.2,
  },
  {
    id: "integrated-air-defense",
    nameFa: "سپر پدافند هوایی یکپارچه",
    nameEn: "Integrated Air Defense",
    desc: "پدافند موشکی پیشرفته که ۳۰٪ از پهپادها و موشک‌های شلیک‌شده دشمن را قبل از برخورد منهدم می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    moneyCost: 50000000000,
    prerequisites: ["border-fortification"],
    effectType: "AIR_DEFENSE_INTERCEPT",
    magnitude: 0.3,
  },
  {
    id: "precision-missiles",
    nameFa: "سامانه‌های بالستیک نقطه‌زن",
    nameEn: "Precision Ballistic Missiles",
    desc: "افزایش ۲۵٪ قدرت تهاجمی موشک‌ها در حملات پیش‌دستانه به یگان‌های دشمن.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    moneyCost: 55000000000,
    prerequisites: ["tactical-drones"],
    effectType: "PRECISION_STRIKE",
    magnitude: 0.3,
  },
  {
    id: "electronic-warfare",
    nameFa: "جنگ الکترونیک و دفاع سایبری",
    nameEn: "Electronic Warfare Suite",
    desc: "بی‌اثر کردن ۵۰٪ از برتری هوایی دشمن در نبردها و افزایش ۲۰٪ شانس فرار یگان‌های خودی.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 3,
    moneyCost: 130000000000,
    prerequisites: ["integrated-air-defense", "precision-missiles"],
    effectType: "ELECTRONIC_WARFARE",
    magnitude: 0.5,
  },
  {
    id: "global-influence",
    nameFa: "دیپلماسی تجاری کلان",
    nameEn: "Commercial Diplomacy",
    desc: "انعقاد موافقت‌نامه‌های گمرکی که درآمد حاصل از تعرفه‌های تجاری را ۱۵٪ افزایش می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    moneyCost: 12000000000,
    prerequisites: [],
    effectType: "TARIFF_REVENUE_BOOST",
    magnitude: 0.15,
  },
  {
    id: "trade-diplomacy",
    nameFa: "تابش رسانه‌ای و دیپلماتیک",
    nameEn: "Cultural Radiance",
    desc: "ارتقای تصویر بین‌المللی که ۱۰ واحد افزایش فوری و دائمی در اعتبار جهانی ایجاد می‌کند.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    moneyCost: 22000000000,
    prerequisites: [],
    effectType: "REPUTATION_FLAT_BOOST",
    magnitude: 10,
  },
  {
    id: "reputation-recovery",
    nameFa: "هژمونی رسانه‌های بین‌المللی",
    nameEn: "Media Hegemony",
    desc: "کنترل افکار عمومی که ۵۰٪ از افت ثبات ناشی از مالیات‌های سنگین را خنثی می‌کند.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    moneyCost: 40000000000,
    prerequisites: ["global-influence"],
    effectType: "TAX_STABILITY_DISCOUNT",
    magnitude: 0.5,
  },
  {
    id: "proxy-network",
    nameFa: "شبکه جاسوسی و عملیات سایبری",
    nameEn: "Covert Intelligence Network",
    desc: "کاهش ۲۵٪ هزینه اجرای تمام سطوح عملیات‌های ویژه و خرابکاری اطلاعاتی.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    moneyCost: 45000000000,
    prerequisites: ["trade-diplomacy"],
    effectType: "PROXY_COST_DISCOUNT",
    magnitude: 0.25,
  },
  {
    id: "security-alliance",
    nameFa: "پیمان امنیت فراملی و هژمونی",
    nameEn: "Transnational Security Alliance",
    desc: "تسهیل شگفت‌انگیز عقد ائتلاف‌های دفاعی با کاهش ۳۰ واحدی آستانه پذیرش نظر کشورهای خارجی.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 3,
    moneyCost: 110000000000,
    prerequisites: ["reputation-recovery", "proxy-network"],
    effectType: "DIPLOMATIC_THRESHOLD_BOOST",
    magnitude: 30,
  },
];
