import { Nation } from "@/domain/nation/nation.schema";

export const DEFAULT_NATION_MOCK: Nation = {
  id: "IRN",
  name: "ایران",
  isAi: false,
  isAlive: true,
  flagCode: "IR",
  taxRate: 15,
  tariffRate: 15,
  treasury: 100000,
  nationalDebt: 0,
  industrialLevel: 1,
  navalFleet: 0,
  government: {
    type: "DEMOCRACY",
    stability: 50,
    turnsInPower: 1,
  },
  military: {
    infantry: 100,
    armor: 20,
    airDefense: 10,
    airForce: 20,
    droneMissile: 5,
    experience: 10,
    techLevel: 1,
    branchTech: {
      infantry: 1,
      armor: 1,
      airDefense: 1,
      airForce: 1,
      droneMissile: 1,
    },
  },
  recruitmentQueue: [],
  relations: {},
  activeModifiers: [],
  globalReputation: 50,
  executedEspionageTiers: [],
  warFocusTargetId: null,
  postWarCooldownTurns: 0,
};
