import { Nation } from "@/domain/nation/nation.schema";

export const DEFAULT_NATION_MOCK: Nation = {
  id: "IRN",
  name: "ایران",
  isAi: false,
  isAlive: true,
  flagCode: "IR",
  economicStance: "BALANCED_MIXED",
  treasury: 50_000_000_000,
  nationalDebt: 0,
  industrialLevel: 1.0,
  equipmentTechLevel: 1.0,
  factoryTiers: [{ techLevel: 1.0, count: 20 }],
  navalFleet: 0,
  government: {
    type: "DEMOCRACY",
    stability: 50,
    turnsInPower: 1,
  },
  military: {
    infantry: 100,
    armor: 20,
    airDefense: 10,
    airForce: 15,
    droneMissile: 50,
    techLevel: 1.0,
  },
  relations: {},
  activeModifiers: [],
  globalReputation: 50,
  executedEspionageTiers: [],
  attackedTargetIdsThisTurn: [],
  warFocusTargetId: null,
  postWarCooldownTurns: 0,
  doctrine: "DOMESTIC_INDUSTRIALIST",
  securityGuarantorId: null,
  isEmergencyProtectorate: false,
};
