import { Nation } from "@/domain/nation/nation.schema";

export const DEFAULT_NATION_MOCK: Nation = {
  id: "IRN",
  name: "ایران",
  isAi: false,
  isAlive: true,
  flagCode: "IR",
  rank: 1,
  perCapitaProductivity: 5113,
  maxPopulationCapacity: 84210526,
  taxRate: 15,
  tariffRate: 10,
  treasury: 100000,
  nationalDebt: 0,
  population: 80000000,
  industrialLevel: 1,
  government: {
    type: "DEMOCRACY",
    stability: 50,
    turnsInPower: 1,
  },
  military: {
    infantry: 100,
    armor: 20,
    airDefense: 10,
    airForce: 20,
    droneMissile: 5,
    navalFleet: 5,
    experience: 10,
    techLevel: 1,
    branchTech: {
      infantry: 1,
      armor: 1,
      airDefense: 1,
      airForce: 1,
      droneMissile: 1,
      navalFleet: 1,
    },
  },
  recruitmentQueue: [],
  geography: {
    landNeighbors: [],
    seaNeighbors: [],
    hasSeaAccess: true,
    territoryPixelCount: 1000,
    infrastructureLevel: 1,
  },
  relations: {},
  activeModifiers: [],
  globalReputation: 50,
  doctrines: { unlockedDoctrines: [] },
  provinceIds: [],
  executedEspionageTiers: [],
  warFocusTargetId: null,
};
