export const ECONOMY_CONFIG = {
  STARTING_TREASURY_RATIO: 0.05,
  DOMESTIC_REVENUE_RATIO: 0.08,
  EXPORT_POWER_RATIO: 0.1,
  TRANSIT_GATEWAY_RATIO: 0.0003,
  FOREIGN_AID_RATIO: 0.005,
  WAR_DEPLOYMENT_COST_RATIO: 0.05,
  DEFAULT_AI_REVENUE_MULTIPLIER: 1.4,
} as const;
