import { NavigationNode } from "../types/navigation-params.schema";

export const NAVIGATION_TREE_NODES: NavigationNode[] = [
  {
    id: "overview-general",
    tab: "overview",
    title: "شناسنامه عمومی و نما",
    description: "پایش زنده اقتصاد، جمعیت، منابع و پایداری داخلی کشور",
    category: "نمای کلی",
    iconName: "LayoutDashboard",
    keywords: ["نما", "اطلاعات", "کشور", "جمعیت", "شناسنامه"],
  },
  {
    id: "military-forces",
    tab: "military",
    subTab: "forces",
    title: "موجودی و قدرت ارتش",
    description: "مشاهده یگان‌های پیاده‌نظام، نیروی هوایی و پهپادها",
    category: "نظامی",
    iconName: "Swords",
    keywords: ["ارتش", "نیروها", "پیاده نظام", "جنگنده", "پهپاد"],
  },
  {
    id: "military-recruitment",
    tab: "military",
    subTab: "expansion",
    title: "استخدام و گسترش نیروها",
    description: "سفارش ساخت پیاده‌نظام، جنگنده و پهپاد جدید",
    category: "نظامی",
    iconName: "PlusCircle",
    keywords: ["استخدام", "خرید", "سرباز", "ساخت", "تجهیزات"],
  },
  {
    id: "politics-tax",
    tab: "politics",
    subTab: "tax",
    title: "تنظیم مالیات و تعرفه",
    description: "مدیریت نرخ مالیات کشوری و تعرفه واردات گمرکی",
    category: "سیاست",
    iconName: "Landmark",
    keywords: ["مالیات", "تعرفه", "گمرک", "درآمد"],
  },
  {
    id: "politics-loans",
    tab: "politics",
    subTab: "loans",
    title: "بانک جهانی و وام‌ها",
    description: "دریافت تسهیلات و وام اضطراری و تسویه بدهی ملی",
    category: "سیاست",
    iconName: "Coins",
    keywords: ["وام", "بدهی", "بانک", "خزانه"],
  },
  {
    id: "market-oil",
    tab: "market",
    subTab: "oil",
    title: "بورس نفت خام",
    description: "خرید و فروش مستقیم بشکه‌های نفت در بازار جهانی",
    category: "بازار",
    iconName: "Fuel",
    keywords: ["نفت", "انرژی", "خرید نفت", "فروش نفت", "بورس"],
  },
  {
    id: "market-steel",
    tab: "market",
    subTab: "steel",
    title: "بورس فولاد صنعتی",
    description: "خرید و فروش فولاد سنگین صنعتی در بورس کالا",
    category: "بازار",
    iconName: "Wrench",
    keywords: ["فولاد", "صنعت", "خرید فولاد", "فروش فولاد"],
  },
  {
    id: "proxy-operations",
    tab: "proxy",
    subTab: "allocate",
    title: "عملیات نیابتی و نفوذ",
    description: "اختصاص بودجه نفوذ برای تضعیف ثبات کشورهای متخاصم",
    category: "نیابتی",
    iconName: "Flame",
    keywords: ["نیابتی", "کودتا", "نفوذ", "بودجه", "تخریب"],
  },
  {
    id: "diplomacy-relations",
    tab: "diplomacy",
    subTab: "relations",
    title: "روابط دیپلماتیک",
    description: "مدیریت معاهدات، پیشنهاد عدم تخاصم و اتحاد",
    category: "دیپلماسی",
    iconName: "Users",
    keywords: ["دیپلماسی", "صلح", "اتحاد", "پیمان"],
  },
  {
    id: "research-doctrines",
    tab: "research",
    subTab: "doctrines",
    title: "درخت دکترین‌های راهبردی",
    description: "آنلاک شاخه‌های صنعتی، دفاع ناهمگون و هژمونی",
    category: "پژوهش",
    iconName: "Cpu",
    keywords: ["پژوهش", "دکترین", "تحقیق", "ارتقا"],
  },
  {
    id: "abilities-special",
    tab: "abilities",
    subTab: "abilities",
    title: "توانمندی‌های ویژه حکومتی",
    description: "فعال‌سازی فرمان‌های ویژه مانند حکومت نظامی و نشست دیپلماتیک",
    category: "توانمندی",
    iconName: "Zap",
    keywords: ["توانمندی", "قدرت", "حکومت نظامی", "نشست"],
  },
  {
    id: "reports-history",
    tab: "reports",
    subTab: "reports",
    title: "گزارش‌های حاکمیت و رویدادهای ملی",
    description: "بایگانی آمار رویدادها و ارزیابی‌های اطلاعاتی کشوری",
    category: "گزارش‌ها",
    iconName: "FileText",
    keywords: ["گزارش", "آمار", "اطلاعات", "حاکمیت"],
  },
];
