import { CountryProfile } from "../types";

export const centralAsiaProfiles: CountryProfile[] = [
  {
    id: 16,
    code: "KAZ",
    nameEn: "Kazakhstan",
    nameFa: "قزاقستان",
    gdp: 220000000000,
    population: 20000000,
    traits: ["OIL_RICH"],
    flagCode: "KZ",
    startingTreasury: 250000,
    startingInfantry: 110,
    startingAirForce: 30,
    startingDroneMissile: 5,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 17,
    code: "UZB",
    nameEn: "Uzbekistan",
    nameFa: "ازبکستان",
    gdp: 80000000000,
    population: 36000000,
    traits: ["FRAGILE_ECONOMY"],
    flagCode: "UZ",
    startingTreasury: 110000,
    startingInfantry: 90,
    startingAirForce: 25,
    startingDroneMissile: 5,
    startingTechLevel: 2,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 108,
    code: "MNG",
    nameEn: "Mongolia",
    nameFa: "مغولستان",
    gdp: 17000000000,
    population: 3400000,
    traits: ["ISOLATED_SOCIETY"],
    flagCode: "MN",
    startingTreasury: 80000,
    startingInfantry: 50,
    startingAirForce: 10,
    startingDroneMissile: 0,
    startingTechLevel: 1,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 115,
    code: "TJK",
    nameEn: "Tajikistan",
    nameFa: "تاجیکستان",
    gdp: 10000000000,
    population: 10000000,
    traits: ["FRAGILE_ECONOMY"],
    flagCode: "TJ",
    startingTreasury: 60000,
    startingInfantry: 45,
    startingAirForce: 10,
    startingDroneMissile: 0,
    startingTechLevel: 1,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 116,
    code: "KGZ",
    nameEn: "Kyrgyzstan",
    nameFa: "قرقیزستان",
    gdp: 11000000000,
    population: 7000000,
    traits: ["FRAGILE_ECONOMY"],
    flagCode: "KG",
    startingTreasury: 60000,
    startingInfantry: 40,
    startingAirForce: 10,
    startingDroneMissile: 0,
    startingTechLevel: 1,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 117,
    code: "TKM",
    nameEn: "Turkmenistan",
    nameFa: "ترکمنستان",
    gdp: 45000000000,
    population: 6500000,
    traits: ["OIL_RICH", "ISOLATED_SOCIETY"],
    flagCode: "TM",
    startingTreasury: 140000,
    startingInfantry: 60,
    startingAirForce: 15,
    startingDroneMissile: 0,
    startingTechLevel: 2,
    startingGovernment: "DEMOCRACY",
  },
];
