import { CountryProfile } from "../types";

export const eastAsiaProfiles: CountryProfile[] = [
  {
    id: 106,
    code: "PRK",
    nameEn: "North Korea",
    nameFa: "کره شمالی",
    gdp: 20000000000,
    population: 26000000,
    traits: ["MILITARISTIC", "ISOLATED_SOCIETY"],
    flagCode: "KP",
    startingTreasury: 150000,
    startingInfantry: 700,
    startingAirForce: 40,
    startingDroneMissile: 50,
    startingTechLevel: 2,
    startingGovernment: "COMMUNISM",
  },
  {
    id: 107,
    code: "KOR",
    nameEn: "South Korea",
    nameFa: "کره جنوبی",
    gdp: 1700000000000,
    population: 51000000,
    traits: ["INDUSTRIAL_HUB", "MILITARISTIC"],
    flagCode: "KR",
    startingTreasury: 550000,
    startingInfantry: 450,
    startingAirForce: 90,
    startingDroneMissile: 30,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 150,
    code: "CHN",
    nameEn: "China",
    nameFa: "چین",
    gdp: 18000000000000,
    population: 1400000000,
    traits: ["INDUSTRIAL_HUB", "MILITARISTIC"],
    flagCode: "CN",
    startingTreasury: 900000,
    startingInfantry: 1200,
    startingAirForce: 200,
    startingDroneMissile: 70,
    startingTechLevel: 4,
    startingGovernment: "COMMUNISM",
  },
  {
    id: 151,
    code: "TWN",
    nameEn: "Taiwan",
    nameFa: "تایوان",
    gdp: 760000000000,
    population: 23900000,
    traits: ["ISLAND_FORTRESS", "INDUSTRIAL_HUB"],
    flagCode: "TW",
    startingTreasury: 380000,
    startingInfantry: 200,
    startingAirForce: 65,
    startingDroneMissile: 20,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 166,
    code: "JPN",
    nameEn: "Japan",
    nameFa: "ژاپن",
    gdp: 4400000000000,
    population: 124000000,
    traits: ["ISLAND_FORTRESS", "INDUSTRIAL_HUB"],
    flagCode: "JP",
    startingTreasury: 750000,
    startingInfantry: 250,
    startingAirForce: 75,
    startingDroneMissile: 20,
    startingTechLevel: 5,
    startingGovernment: "DEMOCRACY",
  },
];
