export interface LocalizedCountryName {
  en: string;
  fa: string;
}

export const COUNTRY_NAMES_DATA: Record<string, LocalizedCountryName> = {
  IRN: { en: "Iran", fa: "ایران" },
  USA: { en: "United States of America", fa: "ایالات متحده آمریکا" },
  CHN: { en: "China", fa: "چین" },
  RUS: { en: "Russia", fa: "روسیه" },
  DEU: { en: "Germany", fa: "آلمان" },
  JPN: { en: "Japan", fa: "ژاپن" },
  GBR: { en: "United Kingdom", fa: "بریتانیا" },
  IND: { en: "India", fa: "هند" },
  FRA: { en: "France", fa: "فرانسه" },
  ITA: { en: "Italy", fa: "ایتالیا" },
  CAN: { en: "Canada", fa: "کانادا" },
  BRA: { en: "Brazil", fa: "برزیل" },
  ESP: { en: "Spain", fa: "اسپانیا" },
  KOR: { en: "South Korea", fa: "کره جنوبی" },
  AUS: { en: "Australia", fa: "استرالیا" },
  MEX: { en: "Mexico", fa: "مکزیک" },
  TUR: { en: "Turkey", fa: "ترکیه" },
  IDN: { en: "Indonesia", fa: "اندونزی" },
  NLD: { en: "Netherlands", fa: "هلند" },
  SAU: { en: "Saudi Arabia", fa: "عربستان سعودی" },
  CHE: { en: "Switzerland", fa: "سوئیس" },
  POL: { en: "Poland", fa: "لهستان" },
  TWN: { en: "Taiwan", fa: "تایوان" },
  BEL: { en: "Belgium", fa: "بلژیک" },
  IRL: { en: "Ireland", fa: "ایرلند" },
  ARG: { en: "Argentina", fa: "آرژانتین" },
  SWE: { en: "Sweden", fa: "سوئد" },
  ISR: { en: "Israel", fa: "اسرائیل" },
  AUT: { en: "Austria", fa: "اتریش" },
  THA: { en: "Thailand", fa: "تایلند" },
  ARE: { en: "United Arab Emirates", fa: "امارات متحده عربی" },
  NOR: { en: "Norway", fa: "نروژ" },
  VNM: { en: "Vietnam", fa: "ویتنام" },
  PHL: { en: "Philippines", fa: "فیلیپین" },
  MYS: { en: "Malaysia", fa: "مالزی" },
  DNK: { en: "Denmark", fa: "دانمارک" },
  BGD: { en: "Bangladesh", fa: "بنگلادش" },
  COL: { en: "Colombia", fa: "کلمبیا" },
  ROU: { en: "Romania", fa: "رومانی" },
  ZAF: { en: "South Africa", fa: "آفریقای جنوبی" },
  PAK: { en: "Pakistan", fa: "پاکستان" },
  CZE: { en: "Czechia", fa: "جمهوری چک" },
  EGY: { en: "Egypt", fa: "مصر" },
  CHL: { en: "Chile", fa: "شیلی" },
  PRT: { en: "Portugal", fa: "پرتغال" },
  PER: { en: "Peru", fa: "پرو" },
  FIN: { en: "Finland", fa: "فنلاند" },
  KAZ: { en: "Kazakhstan", fa: "قزاقستان" },
  NGA: { en: "Nigeria", fa: "نیجریه" },
  DZA: { en: "Algeria", fa: "الجزایر" },
  GRC: { en: "Greece", fa: "یونان" },
  IRQ: { en: "Iraq", fa: "عراق" },
  NZL: { en: "New Zealand", fa: "نیوزیلند" },
  HUN: { en: "Hungary", fa: "مجارستان" },
  QAT: { en: "Qatar", fa: "قطر" },
  UKR: { en: "Ukraine", fa: "اوکراین" },
  MAR: { en: "Morocco", fa: "مراکش" },
  KWT: { en: "Kuwait", fa: "کویت" },
  SVK: { en: "Slovakia", fa: "اسلواکی" },
  UZB: { en: "Uzbekistan", fa: "ازبکستان" },
  KEN: { en: "Kenya", fa: "کنیا" },
  ECU: { en: "Ecuador", fa: "اکوادور" },
  BGR: { en: "Bulgaria", fa: "بلغارستان" },
  ETH: { en: "Ethiopia", fa: "اتیوپی" },
  GTM: { en: "Guatemala", fa: "گواتمالا" },
  OMN: { en: "Oman", fa: "عمان" },
  LKA: { en: "Sri Lanka", fa: "سری‌لانکا" },
  CUB: { en: "Cuba", fa: "کوبا" },
  HRV: { en: "Croatia", fa: "کرواسی" },
  SRB: { en: "Serbia", fa: "صربستان" },
  VEN: { en: "Venezuela", fa: "ونزوئلا" },
  COD: { en: "Dem. Rep. Congo", fa: "کنگو دموکراتیک" },
  TZA: { en: "Tanzania", fa: "تانزانیا" },
  BLR: { en: "Belarus", fa: "بلاروس" },
  AZE: { en: "Azerbaijan", fa: "آذربایجان" },
  BOL: { en: "Bolivia", fa: "بولیوی" },
  JOR: { en: "Jordan", fa: "اردن" },
  CMR: { en: "Cameroon", fa: "کامرون" },
  TKM: { en: "Turkmenistan", fa: "ترکمنستان" },
  LBY: { en: "Libya", fa: "لیبی" },
  CYP: { en: "Cyprus", fa: "قبرس" },
  ISL: { en: "Iceland", fa: "ایسلند" },
  ARM: { en: "Armenia", fa: "ارمنستان" },
  PRK: { en: "North Korea", fa: "کره شمالی" },
  SYR: { en: "Syria", fa: "سوریه" },
  BFA: { en: "Burkina Faso", fa: "بورکینافاسو" },
  MNG: { en: "Mongolia", fa: "مغولستان" },
  LBN: { en: "Lebanon", fa: "لبنان" },
  MDG: { en: "Madagascar", fa: "ماداگاسکار" },
  KGZ: { en: "Kyrgyzstan", fa: "قرقیزستان" },
  YEM: { en: "Yemen", fa: "یمن" },
  AFG: { en: "Afghanistan", fa: "افغانستان" },
  TJK: { en: "Tajikistan", fa: "تاجیکستان" },
  SDS: { en: "S. Sudan", fa: "سودان جنوبی" },
  DJI: { en: "Djibouti", fa: "جیبوتی" },
  GRL: { en: "Greenland", fa: "گرینلند" },
  SOL: { en: "Somaliland", fa: "سومالی‌لند" },
};
