export const DIPLOMACY_CONFIG = {
  POST_WAR_COOLDOWN_TURNS: 8,
  PROPOSAL_EXPIRY_TURNS: 2,
  MAX_TENSION: 100,
  MIN_TENSION: 0,
  MAX_ALIGNMENT: 100,
  MIN_ALIGNMENT: -100,
  STRATEGIC_PARTNERSHIP_ENTRY_FEE_RATIO: 0.03,
  STRATEGIC_PARTNERSHIP_DIVIDEND_RATIO: 0.006,
} as const;
