export interface ResearchNode {
  id: string;
  nameFa: string;
  desc: string;
  branch: "INDUSTRIAL_TECH" | "ASYMMETRIC_MILITARY" | "DIPLOMATIC_HEGEMONY";
  tier: 1 | 2 | 3;
  moneyCost: number;
  prerequisites: string[];
}

export const COMPREHENSIVE_RESEARCH_TREE: ResearchNode[] = [
  {
    id: "automated-supply-chain",
    nameFa: "زنجیره تأمین هوشمند",
    desc: "مکانیزه‌سازی زیرساخت‌های لجستیک و انبارداری که ۴٪ به درآمدهای مالیات صنعتی کشور می‌افزاید.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    moneyCost: 25000000000,
    prerequisites: [],
  },
  {
    id: "urban-modernization",
    nameFa: "بهینه‌سازی زیست‌شهری",
    desc: "نوسازی خدمات عمومی و مسکن که ظرفیت جذب جمعیت و بهره‌وری صنعتی شهرها را ارتقا می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 1,
    moneyCost: 30000000000,
    prerequisites: [],
  },
  {
    id: "fiscal-stabilization",
    nameFa: "مهار اصطکاک مالیاتی",
    desc: "تعدیل نارضایتی‌های عمومی که ۳۰٪ از افت ثبات ناشی از نرخ‌های مالیاتی بالا را خنثی می‌کند.",
    branch: "INDUSTRIAL_TECH",
    tier: 2,
    moneyCost: 90000000000,
    prerequisites: ["automated-supply-chain"],
  },
  {
    id: "heavy-industry-scale",
    nameFa: "مجتمع‌های صنایع سنگین",
    desc: "توسعه مراکز پتروشیمی و ذوب فلزات که بازدهی مالیاتی ناخالص ملی را ۸٪ ارتقا می‌دهد.",
    branch: "INDUSTRIAL_TECH",
    tier: 2,
    moneyCost: 120000000000,
    prerequisites: ["automated-supply-chain", "urban-modernization"],
  },
  {
    id: "cybernetic-optimization",
    nameFa: "اتوماسیون سایبرنتیک",
    desc: "به‌کارگیری هوش مصنوعی در ساختار صنعتی که ۱۵٪ هزینه نگهداری ارتش را کاسته و ۶٪ درآمد مالیاتی را بیشتر می‌کند.",
    branch: "INDUSTRIAL_TECH",
    tier: 3,
    moneyCost: 450000000000,
    prerequisites: ["heavy-industry-scale", "fiscal-stabilization"],
  },
  {
    id: "tactical-recon-grid",
    nameFa: "شبکه پایش پهپادی تاکتیکی",
    desc: "پایش مداوم داده‌های میدان که قدرت تخریب اسکادران‌های پهپادی و موشکی را ۱۵٪ افزایش می‌دهد.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    moneyCost: 25000000000,
    prerequisites: [],
  },
  {
    id: "layered-air-shield",
    nameFa: "سپر پدافندی چندلایه",
    desc: "سامانه یکپارچه دفاع هوایی که ضریب رهگیری موفق موشک‌ها و پهپادهای مهاجم را ۲۰٪ بالا می‌برد.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 1,
    moneyCost: 35000000000,
    prerequisites: [],
  },
  {
    id: "precision-strike-doctrine",
    nameFa: "دکترین ضربات دوربرد نقطه‌زن",
    desc: "هدایت بالستیک پیشرفته که ۲۰٪ به تخریب مستقیم موشکی و ۱۰٪ به توان یگان‌های پهپادی اضافه می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    moneyCost: 110000000000,
    prerequisites: ["tactical-recon-grid"],
  },
  {
    id: "counter-ew-defense",
    nameFa: "پادکار جنگ الکترونیک",
    desc: "سامانه‌های فریب راداری و دفاع سایبری که برتری هوایی مطلق دشمن در نبردها را مهار می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 2,
    moneyCost: 130000000000,
    prerequisites: ["layered-air-shield"],
  },
  {
    id: "combined-arms-supremacy",
    nameFa: "برتری نبرد ترکیبی",
    desc: "هم‌افزایی همه‌جانبه ارکان دفاعی که ۱۵٪ به رهگیری پدافند و ۱۰٪ به آسیب پیش‌دستانه موشکی اضافه می‌کند.",
    branch: "ASYMMETRIC_MILITARY",
    tier: 3,
    moneyCost: 500000000000,
    prerequisites: ["precision-strike-doctrine", "counter-ew-defense"],
  },
  {
    id: "customs-harmonization",
    nameFa: "تسهیل کریدورهای تجاری",
    desc: "انعقاد تفاهم‌نامه‌های بین‌المللی که درآمد حاصل از تعرفه‌های گمرکی را ۱۲٪ افزایش می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    moneyCost: 20000000000,
    prerequisites: [],
  },
  {
    id: "strategic-diplomacy",
    nameFa: "دیپلماسی رسانه‌ای و عمومی",
    desc: "تابش قدرت نرم که سرعت بازیابی و بهبود اعتبار بین‌المللی در دوران صلح را ۲۰٪ شتاب می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 1,
    moneyCost: 30000000000,
    prerequisites: [],
  },
  {
    id: "deep-espionage-network",
    nameFa: "شبکه اشراف اطلاعاتی پنهان",
    desc: "توسعه پایگاه‌های نفوذ خارجی که ۲۵٪ هزینه تمامی سطوح عملیات‌های ویژه و خرابکاری را کاهش می‌دهد.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    moneyCost: 95000000000,
    prerequisites: ["strategic-diplomacy"],
  },
  {
    id: "preferential-trade-pacts",
    nameFa: "پیمان‌های تجاری ترجیحی",
    desc: "توافقات چندجانبه بازرگانی که درآمد حاصل از تعرفه‌ها را ۱۰٪ دیگر تقویت می‌کند.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 2,
    moneyCost: 115000000000,
    prerequisites: ["customs-harmonization"],
  },
  {
    id: "hegemonic-diplomatic-order",
    nameFa: "نظم نوین دیپلماتیک فراملی",
    desc: "تسلط بر موازنه‌های جهانی که ۲۵٪ بازیابی اعتبار و ۱۰٪ تخفیف اضافه بر عملیات‌های سرّی فراهم می‌کند.",
    branch: "DIPLOMATIC_HEGEMONY",
    tier: 3,
    moneyCost: 480000000000,
    prerequisites: ["deep-espionage-network", "preferential-trade-pacts"],
  },
];
