export const VICTORY_CONFIG = {
  TERRITORIAL_DOMINANCE_TARGET_RATIO: 0.65,
  ECONOMIC_DOMINANCE_TARGET_RATIO: 0.65,
  TERRITORIAL_DOMINANCE_TARGET_PCT: 65,
  ECONOMIC_DOMINANCE_TARGET_PCT: 65,
} as const;
