import { CountryProfile } from "../types";

export const westernEuropeProfiles: CountryProfile[] = [
  {
    id: 54,
    code: "FRA",
    nameEn: "France",
    nameFa: "فرانسه",
    gdp: 2900000000000,
    population: 68000000,
    traits: ["INDUSTRIAL_HUB", "MILITARISTIC"],
    flagCode: "FR",
    startingTreasury: 620000,
    startingInfantry: 220,
    startingAirForce: 70,
    startingDroneMissile: 25,
    startingTechLevel: 5,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 125,
    code: "AUT",
    nameEn: "Austria",
    nameFa: "اتریش",
    gdp: 480000000000,
    population: 9000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "AT",
    startingTreasury: 310000,
    startingInfantry: 50,
    startingAirForce: 20,
    startingDroneMissile: 2,
    startingTechLevel: 3,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 132,
    code: "DEU",
    nameEn: "Germany",
    nameFa: "آلمان",
    gdp: 4300000000000,
    population: 84000000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "DE",
    startingTreasury: 750000,
    startingInfantry: 150,
    startingAirForce: 55,
    startingDroneMissile: 15,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 138,
    code: "CHE",
    nameEn: "Switzerland",
    nameFa: "سوئیس",
    gdp: 800000000000,
    population: 8800000,
    traits: ["SOVEREIGN_FORTRESS", "INDUSTRIAL_HUB"],
    flagCode: "CH",
    startingTreasury: 480000,
    startingInfantry: 60,
    startingAirForce: 35,
    startingDroneMissile: 5,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 140,
    code: "BEL",
    nameEn: "Belgium",
    nameFa: "بلژیک",
    gdp: 580000000000,
    population: 11700000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "BE",
    startingTreasury: 350000,
    startingInfantry: 50,
    startingAirForce: 30,
    startingDroneMissile: 5,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
  {
    id: 141,
    code: "NLD",
    nameEn: "Netherlands",
    nameFa: "هلند",
    gdp: 1000000000000,
    population: 17800000,
    traits: ["INDUSTRIAL_HUB"],
    flagCode: "NL",
    startingTreasury: 420000,
    startingInfantry: 80,
    startingAirForce: 40,
    startingDroneMissile: 10,
    startingTechLevel: 4,
    startingGovernment: "DEMOCRACY",
  },
];
